import React from "react";
import StatsSection from "../common/StatsSection";
import GetMoreMarketsSection from "../common/GetMoreMarketsSection";
import FaqSection from "../common/FaqSection";
import InfoTextSection from "../common/InfoTextSection";
import BenefitGrid from "../common/BenefitGrid";
import HeadingWithDescription from "../common/HeadingWithDescription";
import tradingsignals from "../../assets/tradingsignals.png";
import icon1 from "../../assets/tradingsignals2.svg";
import icon2 from "../../assets/tradingsignals3.svg";
import icon3 from "../../assets/tradingsignals4.svg";
import icon4 from "../../assets/tradingsignals5.svg";
import icon5 from "../../assets/tradingsignals6.svg";

const TradingSignals = () => {
  const benefitsData = [
    {
      icon: icon1,
      title: "Up-to-date",
      description:
        "Get quality trade ideas three times a day, directly in MyFXTM.",
    },
    {
      icon: icon2,
      title: "Multi-asset",
      description:
        "Receive trading plans for FX, stocks, commodities and indices.",
    },
    {
      icon: icon3,
      title: "Actionable",
      description:
        "See specific entry, take-profit, stop-loss and confidence levels.",
    },
    {
      icon: icon4,
      title: "Independent",
      description: "Acuity is a trusted, award-winning, third-party provider.",
    },
    {
      icon: icon5,
      title: "Regulated",
      description:
        "Feel confident knowing Acuity is fully regulated by the FCA.",
    },
  ];

  const sectionData = [
    {
      title: "Forex trading signals straight to your inbox",
      description:
        "We know that finding trading opportunities can be difficult and time-consuming. Receive expertly crafted forex trading signals directly to your inbox with Acuity’s Signal Centre, available exclusively through MyFXTM, making it easier to spot and act on trading opportunities quickly.",
    },
    {
      title: "What is a trading signal?",
      description:
        "Put simply, trading signals are a collection of tools that analyse the price movements of an asset and alert a trader to either buy or sell. They are generated by either technical analysis indicators or mathematical algorithms.",
    },
    {
      title: "What is Acuity Signal Centre?",
      description:
        "Acuity is an award-winning provider of technical analysis and trading plans. Its Signal Centre service combines analyst-led and AI-powered research to provide investors with trading signals on a range of asset classes. Offering specific entry, take-profit and stop-loss levels – as well as ‘confidence indicators’ to suggest likelihood – Signal Centre can help alert you to potential trading opportunities or inform you own analysis.",
    },
  ];
  const faqItems = [
    { question: "What is segregation of funds?" },
    { question: "How does segregation of funds work?" },
    { question: "What are the benefits of segregated funds?" },
    {
      question:
        "What's the difference between mutual funds and segregated funds?",
    },
    { question: "Can you withdraw from segregated funds?" },
  ];
  return (
    <>
      <StatsSection
        title="Trading Signals"
        subtitle="Access real-time trading signals and strategies to stay ahead."
        buttonText="Check Signals"
        image={tradingsignals}
      />
      <InfoTextSection sections={sectionData} />
      <BenefitGrid
        title="The benefits of Signal Centre"
        benefits={benefitsData}
      />

      <HeadingWithDescription
        title="How trading signals work"
        description="Released three times a day before the European, US and Asian sessions, Signal Centre can help you spot high-quality trading opportunities across FX, indices, commodities and stocks.

Although trading signals offer no profit guarantees, they serve as a crucial tool for saving time on technical analysis. Released three times a day, these signals provide entry, stop-loss, and take-profit points to assist you in refining your trading strategies.

"
      />

      <GetMoreMarketsSection />
      <FaqSection faqs={faqItems} />
    </>
  );
};

export default TradingSignals;
